### ISSUE TITLE
unicode test filenames breaks node-tar's ability to unpack npm install from github

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#142]
Only seen on @artemp's osx filesystem, not seeing this on mine.

Need to figure out what msysgit version I used to create the data and look for gochas at https://github.com/msysgit/msysgit/wiki/Git-for-Windows-Unicode-Support

```
6686 error tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622\
464342974126/tmp.tgz
6687 silly gunzTarPerm extractEntry test/data/Clément/long_lat.prj
6688 silly gunzTarPerm modified mode [ 'test/data/Clément/long_lat.prj', 436, 420 ]
6689 silly lockFile 4e826426-mapbox-node-mapnik-data-tile-git git@github.com:mapbox/node-mapnik-data-tile.git
6690 error Error: invalid tar file
6690 error     at Extract.Parse._startEntry (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:144:13)
6690 error     at Extract.Parse._process (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:125:12)
6690 error     at BlockStream.<anonymous> (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:46:8)
6690 error     at BlockStream.EventEmitter.emit (events.js:96:17)
6690 error     at BlockStream._emitChunk (/opt/node/lib/node_modules/npm/node_modules/block-stream/block-stream.j\
```

**Comment by springmeyer** [comment]
not seen this problem for a while I'm assuming something was fixed upstream in npm.
