### ISSUE TITLE
Test failure with 32 bit builds

### ISSUE THREAD

**Issue by tomhughes** [mapnik/node-mapnik#163]
One of the tests passes on 64 bit builds but fails on 32 bit x86:

```
  1) mapnik.Image  should support setting the alpha channel based on the amount of gray:
     AssertionError: 254 == 255
      at Context.<anonymous> (/builddir/build/BUILD/package/test/image.test.js:152:16)
      at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:213:32)
      at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:351:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:397:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:277:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:286:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:234:23)
      at Object._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:254:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by springmeyer** [comment]
I have no easy way to test 32 bit compiles so I don't have any plans to fix this.
