### ISSUE TITLE
test failures if CXXFLAGS="-DCONV_CLIPPER"

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#192]
``` sh
   1) should read back the data tile and render an image with it
    2) should read back the data tile and render an image with it using negative buffer
    3) should read back the data tile and render a grid with it


  186 passing (2s)
  3 failing

  1) mapnik.VectorTile  should read back the data tile and render an image with it:
     Uncaught AssertionError: 26952 == 27091
      at /Users/dane/projects/node-mapnik/test/vector-tile.test.js:298:20

  2) mapnik.VectorTile  should read back the data tile and render an image with it using negative buffer:
     Uncaught AssertionError: 13031 == 13035
      at /Users/dane/projects/node-mapnik/test/vector-tile.test.js:317:20

  3) mapnik.VectorTile  should read back the data tile and render a grid with it:
     Uncaught AssertionError: {"grid":["                                                                ","                                                    deepEqual {"grid":["                                                                ","                                                   
      at /Users/dane/projects/node-mapnik/test/vector-tile.test.js:339:20
```

**Comment by springmeyer** [comment]
stale
