### ISSUE TITLE
"undefined symbol" error on Ubuntu Trusty 32bit 

### ISSUE THREAD

**Issue by sergets** [mapnik/node-mapnik#434]
Hi, sorry if this is a wrong place to ask. I'm trying to get node-mapnik working on a 32-bit Ubuntu Trusty.
So, I've installed mapnik 3.0.0 nightly form PPA repository and node-mapnik external dependencies, and then built node-mapnik from source:
````
$ sudo add-apt-repository ppa:mapnik/nightly-trunk
$ sudo apt-get update
$ sudo apt-get install libmapnik libmapnik-dev protobuf-compiler libprotobuf
$ dpkg -s libmapnik | grep Version
Version: 3.0.0+dev20150418.git.a621022-1~trusty1

$ npm install mapnik --build-from-source
````
Build has passed ok, but when I try to use `mapnik` module, it fails:
````
$ nodejs -e "require('mapnik')"
Error: /home/sergets/www/express/node_modules/mapnik/lib/binding/node-v11-linux-ia32/mapnik.node: undefined symbol: _ZN6mapnik6filter19parse_image_filtersERKSsRSt6vectorINS_4util7variantIINS0_4blurENS0_4grayENS0_14agg_stack_blurENS0_6embossENS0_7sharpenENS0_11edge_detectENS0_5sobelENS0_10x_gradientENS0_10y_gradientENS0_6invertENS0_10scale_hslaENS0_14colorize_alphaENS0_14color_to_alphaEEEESaISJ_EE
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sergets/www/express/node_modules/mapnik/lib/mapnik.js:26:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
````
Is it a known issue? Is there a way to get node-mapnik running on a 32-bit machine?

**Comment by springmeyer** [comment]
Hi @sergets - this is the right place. No this is not a known issue. The reality is that I don't test Mapnik/Node-mapnik on 32 systems anymore, so I don't catch problems like this. One idea would be to try the clang++ compiler instead of g++.

**Comment by springmeyer** [comment]
Closing since I'm not in a position to test or maintain the code for 32 bit systems.
