### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by BHare1985** [mapnik/node-mapnik#439]
Just installed the latest node and ran 'npm install mapnik@3.x' at 'C:\Users\bh\Desktop\Demo3' and everything said it was installed.

Then ran and got this

C:\Users\bh\Desktop\Demo3>node
> var mapnik = require('mapnik');
Error: The specified module could not be found.
C:\Users\bh\Desktop\Demo3\node_modules\mapnik\lib\binding\node-v14-win32-x64\map
nik.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\bh\Desktop\Demo3\node_modules\mapnik\lib\map
nik.js:26:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
>

I am running on Windows 7 Pro 64bit, let me know if you need other information.

**Comment by springmeyer** [comment]
Is this your first time installing node-mapnik on windows, or did you just upgrade to the latest release? If it is your first time then you need to install the `vcredist_x64.exe` for Visual Studio 2014, see  the note at https://github.com/mapnik/node-mapnik#installing and https://github.com/mapnik/node-mapnik/wiki/WindowsBinaries

**Comment by BHare1985** [comment]
That fixed it, was not obvious on the install md but when carefully reading it was more obvious.
