### ISSUE TITLE
ImageView test error on Windows

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#549]
Seeing this in the `mapnik-index` branch but it looks unrelated to the branch so I wonder if this has been going unnoticed in master as well:

```
 1) mapnik.ImageView  should be able to save an ImageView:
     Error: Could not write file to /tmp/mapnik-image-view-saved.png
      at Context.<anonymous> (C:\projects\node-mapnik\test\image_view.test.js:223:14)
      at callFnAsync (C:\projects\node-mapnik\node_modules\mocha\lib\runnable.js:306:8)
      at Test.Runnable.run (C:\projects\node-mapnik\node_modules\mocha\lib\runnable.js:261:7)
      at Runner.runTest (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:421:10)
      at C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:528:12
      at next (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:341:14)
      at C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:351:7
      at next (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:283:14)
      at Object._onImmediate (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:319:5)
 ```

**Comment by BergWerkGIS** [comment]
Didn't see this locally, let's wait for AppVeyor.
