### ISSUE TITLE
Test failures with reportGeometryValidity()

### ISSUE THREAD

**Issue by tomhughes** [mapnik/node-mapnik#569]
Build on linux x86_64 with mapnik 3.09 and mapnik-vector-tile 0.14.1 I'm seeing a few tests failing because `reportGeometryValidity()` is returning either one more or one less error than expected:

```
  1) mapnik.VectorTile  should render a vector_tile of the whole world:
     Uncaught AssertionError: 15 == 14
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1858:24

  2) mapnik.VectorTile  should render a vector_tile of the whole world - area threshold applied:
     Uncaught AssertionError: 15 == 14
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1888:24

  3) mapnik.VectorTile  should render a vector_tile of the whole world - strictly simple applied:
     Uncaught AssertionError: 11 == 10
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1920:24

  4) mapnik.VectorTile  should render a vector_tile of the whole world - simplify_distance applied:
     Uncaught AssertionError: 9 == 10
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1952:24

  5) mapnik.VectorTile  should render a vector_tile of the whole world - strictly simple and simplify distance applied:
     Uncaught AssertionError: 8 == 9
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1984:24

  6) mapnik.VectorTile  should render a vector_tile of the whole world - multi_polygon_union set to false:
     Uncaught AssertionError: 19 == 18
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2016:24

  7) mapnik.VectorTile  should render a vector_tile of the whole world - fill_type set to evenOdd:
     Uncaught AssertionError: 17 == 16
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2048:24

  8) mapnik.VectorTile  should render a vector_tile of the whole world - fill_type set to nonZero:
     Uncaught AssertionError: 15 == 14
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2080:24

  9) mapnik.VectorTile  should render a vector_tile of the whole world - process_all_rings:
     Uncaught AssertionError: 15 == 14
      at /home/tom/rpm/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2112:24
```

As an example, the errors reported by the first of those are:

```
[ { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (1.00872e+07, 2.55361e+06); method: m; operations: i/i; segment IDs {source, multi, ring, segment}: {0, 0, -1, 14}/{0, 2, -1, 3}',
    featureId: 14 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (1.09829e+07, 1.33818e+06); method: i; operations: i/u; segment IDs {source, multi, ring, segment}: {0, 0, -1, 38}/{0, 2, -1, 0}',
    featureId: 18 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-5.80188e+06, -3.73747e+06); method: m; operations: i/i; segment IDs {source, multi, ring, segment}: {0, 0, -1, 79}/{0, 0, -1, 86}',
    featureId: 21 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-1.44485e+07, 7.11684e+06); method: i; operations: i/u; segment IDs {source, multi, ring, segment}: {0, 0, -1, 165}/{0, 30, -1, 2}',
    featureId: 24 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-8.12067e+06, -6.99552e+06); method: m; operations: i/i; segment IDs {source, multi, ring, segment}: {0, 13, -1, 101}/{0, 13, -1, 108}',
    featureId: 33 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-8.26893e+06, 1.2324e+06); method: i; operations: i/u; segment IDs {source, multi, ring, segment}: {0, -1, -1, 1}/{0, -1, -1, 3}',
    featureId: 38 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-1.8296e+06, 1.49694e+06); method: i; operations: u/i; segment IDs {source, multi, ring, segment}: {0, -1, -1, 0}/{0, -1, -1, 3}',
    featureId: 66 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-5.73339e+06, 1.02536e+07); method: t; operations: i/i; segment IDs {source, multi, ring, segment}: {0, 5, 0, 2}/{0, 5, 0, 5}',
    featureId: 71 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (1.35997e+06, 9.66653e+06); method: t; operations: i/i; segment IDs {source, multi, ring, segment}: {0, 0, -1, 68}/{0, 0, -1, 71}',
    featureId: 154 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (2.03506e+06, 8.24786e+06); method: t; operations: u/x; segment IDs {source, multi, ring, segment}: {0, 0, -1, 60}/{0, 0, -1, 55}',
    featureId: 189 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-459845, 7.02487e+06); method: t; operations: i/i; segment IDs {source, multi, ring, segment}: {0, 0, -1, 28}/{0, 1, -1, 0}',
    featureId: 205 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-1.36192e+07, 6.09539e+06); method: m; operations: i/i; segment IDs {source, multi, ring, segment}: {0, 11, -1, 0}/{0, 5, -1, 4}',
    featureId: 207 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (-7.76845e+06, 1.31105e+06); method: t; operations: u/u; segment IDs {source, multi, ring, segment}: {0, 0, -1, 63}/{0, 0, -1, 0}',
    featureId: 212 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (1.1308e+07, 190411); method: i; operations: i/u; segment IDs {source, multi, ring, segment}: {0, 25, -1, 25}/{0, 58, -1, 0}',
    featureId: 223 },
  { layer: 'world',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (4.50061e+06, 9.49042e+06); method: t; operations: u/u; segment IDs {source, multi, ring, segment}: {0, 0, -1, 163}/{0, 0, -1, 166}',
    featureId: 245 } ]
```

I don't know which one is the "extra error" or whether this is anything to worry about, or maybe the tests should just check for a certain minimum number of errors?

**Comment by tomhughes** [comment]
Interestingly two of these do produce the expected number of errors when run on a 32 bit build...

**Comment by flippmoke** [comment]
@tomhughes what version of boost geometry are you using?

**Comment by tomhughes** [comment]
That was probably 1.58.0 I think. I can try 1.59.0 and see what that does?

**Comment by tomhughes** [comment]
Yes, that was 1.58.0 and 1.59.0 passes on 64 bit but does still have two failures on 32 bit. Full results are...

Boost 1.59.0 32 bit:

```
  2) mapnik.VectorTile  should render a vector_tile of the whole world - strictly simple applied:
     Uncaught AssertionError: 9 == 10
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1920:24

  3) mapnik.VectorTile  should render a vector_tile of the whole world - simplify_distance applied:
     Uncaught AssertionError: 11 == 10
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1952:24
```

Boost 1.58.0 64 bit:

```
  1) mapnik.VectorTile  should render a vector_tile of the whole world:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1858:24

  2) mapnik.VectorTile  should render a vector_tile of the whole world - area threshold applied:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1888:24

  3) mapnik.VectorTile  should render a vector_tile of the whole world - strictly simple applied:
     Uncaught AssertionError: 11 == 10
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1920:24

  4) mapnik.VectorTile  should render a vector_tile of the whole world - simplify_distance applied:
     Uncaught AssertionError: 9 == 10
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1952:24

  5) mapnik.VectorTile  should render a vector_tile of the whole world - strictly simple and simplify distance applied:
     Uncaught AssertionError: 8 == 9
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1984:24

  6) mapnik.VectorTile  should render a vector_tile of the whole world - multi_polygon_union set to false:
     Uncaught AssertionError: 19 == 18
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2016:24

  7) mapnik.VectorTile  should render a vector_tile of the whole world - fill_type set to evenOdd:
     Uncaught AssertionError: 17 == 16
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2048:24

  8) mapnik.VectorTile  should render a vector_tile of the whole world - fill_type set to nonZero:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2080:24

  9) mapnik.VectorTile  should render a vector_tile of the whole world - process_all_rings:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2112:24
```

Boost 1.58.0 32 bit:

```
  2) mapnik.VectorTile  should render a vector_tile of the whole world:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1858:24

  3) mapnik.VectorTile  should render a vector_tile of the whole world - area threshold applied:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1888:24

  4) mapnik.VectorTile  should render a vector_tile of the whole world - strictly simple and simplify distance applied:
     Uncaught AssertionError: 8 == 9
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:1984:24

  5) mapnik.VectorTile  should render a vector_tile of the whole world - multi_polygon_union set to false:
     Uncaught AssertionError: 19 == 18
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2016:24

  6) mapnik.VectorTile  should render a vector_tile of the whole world - fill_type set to evenOdd:
     Uncaught AssertionError: 17 == 16
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2048:24

  7) mapnik.VectorTile  should render a vector_tile of the whole world - fill_type set to nonZero:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2080:24

  8) mapnik.VectorTile  should render a vector_tile of the whole world - process_all_rings:
     Uncaught AssertionError: 15 == 14
      at /builddir/build/BUILD/node-mapnik-3.4.11/test/vector-tile.test.js:2112:24
```

**Comment by flippmoke** [comment]
I have been using this tests internally mostly for testing if my processing pipeline is changing so they are nice little alarms for me. However, we probably could make them a little less strict if it really does vary so much based on boost version (which doesn't shock me).

**Comment by kapouer** [comment]
Hello,
on debian/sid with mapnik 3.0.11, mapnik-vector-tile 1.0.6, node-mapnik 3.5.8, and boost 1.59 i get a similar error here:
```
  1) mapnik.VectorTile  should render a vector_tile of the whole world - strictly simple false:
     Uncaught AssertionError: 21 == 20
      at /xxx//node-mapnik/test/vector-tile.test.js:2306:24
```
Only one test fail.

**Comment by flippmoke** [comment]
I believe many of these issues have been fixed in newer versions, closing this ticket for now.
