### ISSUE TITLE
empty arrays in geojson properties

### ISSUE THREAD

**Issue by missinglink** [mapnik/node-mapnik#570]
using `node-mapnik` i'm getting errors such as `Error: geojson_datasource: Failed to parse GeoJSON file` when trying to parse a document which contains a property whos value is an empty array `[]`

eg. this throws an error:
```bash
{
  "type": "Feature",
  "properties": {
    "something": []
  },
  "geometry": {
    "type": "Point",
    "coordinates": [ 1, 1 ]
  }
}
```

this does not:
```bash
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [ 1, 1 ]
  }
}
```

steps to reproduce:
```javascript
var fs = require('fs'),
    mapnik = require('mapnik');

// register plugins
if (mapnik.register_default_input_plugins) mapnik.register_default_input_plugins();

var json = {
  "type": "Feature",
  "properties": {
    "something": []
  },
  "geometry": {
    "type": "Point",
    "coordinates": [ 1, 1 ]
  }
};

// write json to /tmp
fs.writeFileSync( '/tmp/empty_array.geojson', JSON.stringify(json), {encoding:'utf8'});

// load file
var file = new mapnik.Datasource({ type:'geojson', file:'/tmp/empty_array.geojson' });
```

error message:
```bash
var file = new mapnik.Datasource({type:'geojson',file:'/tmp/empty_array.geojso
           ^
Error: geojson_datasource: Failed to parse GeoJSON file '/tmp/empty_array.geojson'
    at Error (native)
    at Object.<anonymous> (/media/black/pix/bug.js:23:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

originally reported here: https://github.com/mapnik/mapnik/issues/3196

**Comment by missinglink** [comment]
closes https://github.com/mapnik/mapnik/issues/3196

**Comment by springmeyer** [comment]
I'm unable to replicate with the latest version of node-mapnik (v3.4.11). What version are you hitting this with?

**Comment by missinglink** [comment]
oh right, apologies. the bug affects the previous version `3.4.10`, when I upgrade to `3.4.11` it seems to have been fixed. thanks for looking in to it!

```bash
$ npm i mapnik@3.4.10

npm http request GET https://registry.npmjs.org/mapnik
npm http 304 https://registry.npmjs.org/mapnik
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mapnik@3.4.10 install /tmp/bug/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.10/node-v14-linux-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.10/node-v14-linux-x64.tar.gz
[mapnik] Success: "/tmp/bug/node_modules/mapnik/lib/binding/node-v14-linux-x64/mapnik.node" is installed via remote
mapnik@3.4.10 node_modules/mapnik
└── nan@2.0.9

$ node bug.js 
/tmp/bug/bug.js:19

var file = new mapnik.Datasource({ type:'geojson', inline: JSON.stringify(json
           ^
Error: geojson_datasource: Failed to parse GeoJSON file from in-memory string
    at Error (native)
    at Object.<anonymous> (/tmp/bug/bug.js:19:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

```bash
$ npm i mapnik@3.4.11

npm http request GET https://registry.npmjs.org/mapnik
npm http 304 https://registry.npmjs.org/mapnik
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mapnik@3.4.11 install /tmp/bug/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.11/node-v14-linux-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.11/node-v14-linux-x64.tar.gz
[mapnik] Success: "/tmp/bug/node_modules/mapnik/lib/binding/node-v14-linux-x64/mapnik.node" is installed via remote
mapnik@3.4.11 node_modules/mapnik
└── nan@2.1.0

$ node bug.js 

$ echo $?
0
```
