### ISSUE TITLE
Unit test failures against Mapnik master

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#582]
@artemp - can you take a look at these tomorrow? Hitting these after updated to latest mapnik master at https://github.com/mapnik/mapnik/commit/03285f60b0b5fb92b289fad9046a253874e776cd.

Note you'll need 125a6f170 to be able to build node-mapnik against mapnik master.

```
  1) mapnik.Image SVG should throw with invalid usage:
     TypeError: SVG parse error:
parse_rect: Invalid width
Failed to parse SVG value: "FAIL"
parse_rect: Invalid height
parse_rect: Invalid rx
parse_rect: Invalid ry
unable to parse invalid svg <path>
unable to parse invalid svg <path> with id 'fail-path'
unable to parse invalid svg <path> with id 'fail-path'
parse_circle: Invalid radius
Failed to parse <polygon> 'points'
Failed to parse <polyline> 'points'
parse_ellipse: Invalid rx
parse_ellipse: Invalid ry
parse_rect: Invalid height

      at test/image.svg.test.js:33:24
      at Function._throws (assert.js:292:5)
      at Function.assert.throws (assert.js:318:11)
      at Context.<anonymous> (test/image.svg.test.js:32:16)

  2) mapnik.Image SVG should error with async file full of errors:
     Uncaught AssertionError: null == true
      at test/image.svg.test.js:114:16

  3) mapnik.Parameters  should be settable on map:

      AssertionError: "<?xmlversion=\"1.0\"encoding=\"utf-8\"?><Mapsrs=\"+proj=longlat+ellps=WGS84+datum=WGS84+no_defs\">\n<Parameters>\n<Parameternam == "<?xmlversion=\"1.0\"encoding=\"utf-8\"?><Mapsrs=\"+proj=longlat+ellps=WGS84+datum=WGS84+no_defs\">\n<Parameters>\n<Parameternam
      + expected - actual

       <?xmlversion="1.0"encoding="utf-8"?><Mapsrs="+proj=longlat+ellps=WGS84+datum=WGS84+no_defs">
       <Parameters>
       <Parametername="a">b</Parameter>
      -<Parametername="bool">0</Parameter>
      +<Parametername="bool">false</Parameter>
       <Parametername="num">12.2</Parameter>
       <Parametername="num2">1</Parameter>
       </Parameters>
       </Map>
      
      at Context.<anonymous> (test/parameters.test.js:41:16)

```

**Comment by springmeyer** [comment]
@artemp fixed the SVG errors by relaxing the expectations. The change causing the `parameters.test.js` to fail is that `<Parameter name="bool">false</Parameter>` becomes `<Parameter name="bool">0</Parameter>` when serialized. This was not happening before. Perhaps it is okay, but kind of add this would all of a sudden starting ocur

**Comment by artemp** [comment]
@springmeyer - fixed by restoring local `variant_io.hpp` whic has specialisation fro  `bool` https://github.com/mapnik/mapnik/commit/c615708a2ab89084adf59442cfa2e8cfdf039aba
