### ISSUE TITLE
Windows install fails

### ISSUE THREAD

**Issue by bmehta** [mapnik/node-mapnik#586]
I ran "npm install mapnik" and it fails with the following error. I have attached the npm debug log
[npm-debug.log.txt](https://github.com/mapnik/node-mapnik/files/101499/npm-debug.log.txt)
. 
@BergWerkGIS I see you have responded to similar issues, so drawing your attention here. Any help will be much appreciated. Thanks.

```
E:\bmehta\programs>npm install mapnik
|
> mapnik@3.4.16 install E:\bmehta\programs\node_modules\mapnik
> node-pre-gyp install --fallback-to-build


E:\bmehta\programs\node_modules\mapnik>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" clean )  else (node  clean )

E:\bmehta\programs\node_modules\mapnik>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" configure --fallback-to-build --module=E:\bmehta\progra
ms\node_modules\mapnik\lib\binding\node-v46-win32-x64\mapnik.node --module_name=
mapnik --module_path=E:\bmehta\programs\node_modules\mapnik\lib\binding\node-v46
-win32-x64 )  else (node  configure --fallback-to-build --module=E:\bmehta\progr
ams\node_modules\mapnik\lib\binding\node-v46-win32-x64\mapnik.node --module_name
=mapnik --module_path=E:\bmehta\programs\node_modules\mapnik\lib\binding\node-v4
6-win32-x64 )
'mapnik-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'mapnik-config --includes' returned exit status 1. while trying to
load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=E:\\bmehta\\programs\\node_modules\\mapnik\\lib\\bin
ding\\node-v46-win32-x64\\mapnik.node" "--module_name=mapnik" "--module_path=E:\
\bmehta\\programs\\node_modules\\mapnik\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd E:\bmehta\programs\node_modules\mapnik
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=E:\bmehta\programs\node_modules\mapnik\lib\binding\node-v4
6-win32-x64\mapnik.node --module_name=mapnik --module_path=E:\bmehta\programs\no
de_modules\mapnik\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\bmehta\programs\node
_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\bmehta\\pro
grams\\node_modules\\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "ins
tall" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\bmehta\programs\node_modules\mapnik
node-pre-gyp ERR! node -v v4.2.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
```

**Comment by springmeyer** [comment]
We don't support node 4x on Windows. Please stick with Node v0.10.x, v0.12.x, or v5. For more details see https://github.com/mapnik/node-mapnik/wiki/WindowsBinaries.

**Comment by bmehta** [comment]
Thanks. Will give v5 a shot tomorrow.

**Comment by DNature** [comment]
I'm having same issues here. with these spec

tried 
> Ubuntu 20.04
> Node v10.22.1, 12.18.4
> NPM v6.14.6

But i'm getting the following errors 

```bash
⋊> ~/D/f/m/example yarn add mapnik@4.5.2                                                                                        10:43:19
yarn add v1.20.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/divine/Documents/freelance/mapnik/example/node_modules/mapnik: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/divine/Documents/freelance/mapnik/example/node_modules/mapnik
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@12.18.4 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/divine/Documents/freelance/mapnik/example/node_modules/mapnik/lib/binding/mapnik.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.2/Release/linux-x64.tar.gz
......
```
