### ISSUE TITLE
Mapnik fails with "cannot find mapnik.node"

### ISSUE THREAD

**Issue by bmehta** [mapnik/node-mapnik#587]
Seeing this error on Windows Server 2008 R2 when mapnik tries to run. Confirmed that mapnik.node exists in ~\node_modules\mapnik\lib\binding\node-v47-win32-x64. Can you help?

module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\E:\bmehta\projects\mbtiles-automation\node_modules\mapnik\lib\binding\node-v
47-win32-x64\mapnik.node
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (E:\bmehta\projects\mbtiles-automation\node_modules\ma
pnik\lib\mapnik.js:31:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by BergWerkGIS** [comment]
Do you have the `Visual C++ Redistributable Packages for Visual Studio 2015` installed?
See https://github.com/mapnik/node-mapnik#windows-specific

**Comment by bmehta** [comment]
Just installed it and it works. Thanks.
