### ISSUE TITLE
Error install node-mapnik on Raspberry Pi 3

### ISSUE THREAD

**Issue by tuanpmt** [mapnik/node-mapnik#628]
Hello,
I've got error when try to install on Raspberry pi 3 - 2016-03-18-raspbian-jessie
gcc version 4.9.2 (Raspbian 4.9.2-10) 
This is output:

```
# error This version of node/NAN/v8 requires a C++11 compiler
   ^
In file included from /home/pi/.node-gyp/5.10.1/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:45,
                 from ../src/utils.hpp:7,
                 from ../src/mapnik_logger.cpp:1:
```

and a lot of errors after that:

```
mapnik.target.mk:221: recipe for target 'Release/obj.target/mapnik/src/mapnik_logger.o' failed
make: *** [Release/obj.target/mapnik/src/mapnik_logger.o] Error 1
make: Leaving directory '/home/pi/temp/node-mapnik/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/temp/node-mapnik/lib/binding/node-v47-linux-arm/mapnik.node" "--module_name=mapnik" "--module_path=/home/pi/temp/node-mapnik/lib/binding/node-v47-linux-arm"
gyp ERR! cwd /home/pi/temp/node-mapnik
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/temp/node-mapnik/lib/binding/node-v47-linux-arm/mapnik.node --module_name=mapnik --module_path=/home/pi/temp/node-mapnik/lib/binding/node-v47-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/temp/node-mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 4.1.19-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/temp/node-mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/temp/node-mapnik
node-pre-gyp ERR! node -v v5.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/temp/node-mapnik/lib/binding/node-v47-linux-arm/mapnik.node --module_name=mapnik --module_path=/home/pi/temp/node-mapnik/lib/binding/node-v47-linux-arm' (1)

npm WARN mapnik@3.5.11 No license field.
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! mapnik@3.5.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.5.11 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/temp/node-mapnik/npm-debug.log
```

i'm trying to server pbf mbtiles map for electron application, but failed at mapnik.

Thanks

**Comment by flippmoke** [comment]
You would need a new version of GCC, additionally mapnik requires at least a `C++11` compliant compiler now.
