### ISSUE TITLE
Failing windows test

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#629]
```
 1) mapnik.VectorTile.composite should correctly composite -- numerical precision issue in mapnik vector tile area calculation:
     TypeError: Vector Tile has POLYGON with first ring clockwise. It is not valid according to v2 of VT spec.
      at TypeError (native)
      at C:\projects\node-mapnik\test\vector-tile.composite.test.js:799:19
      at _tryBlock (assert.js:296:5)
      at _throws (assert.js:315:12)
      at Function.assert.doesNotThrow (assert.js:343:3)
      at Context.<anonymous> (C:\projects\node-mapnik\test\vector-tile.composite.test.js:798:16)
      at callFn (C:\projects\node-mapnik\node_modules\mocha\lib\runnable.js:315:21)
      at Test.Runnable.run (C:\projects\node-mapnik\node_modules\mocha\lib\runnable.js:308:7)
      at Runner.runTest (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:422:10)
      at C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:533:12
      at next (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:342:14)
      at C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:352:7
      at next (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (C:\projects\node-mapnik\node_modules\mocha\lib\runner.js:320:5)
```

**Comment by springmeyer** [comment]
fixed by https://github.com/mapbox/mapnik-vector-tile/commit/69aab12cca534fced2aefd2ecce5f4c08facf1ad and upgrading to that code in https://github.com/mapnik/node-mapnik/commit/4059a27b23966ae42840814f4611cdb41a878ecb
