### ISSUE TITLE
issues building on docker

### ISSUE THREAD

**Issue by calvinmetcalf** [mapnik/node-mapnik#699]
using the [default node container](https://github.com/nodejs/docker-node/blob/910443c39c80291f0bf24712d8d94279cf15b7b5/6.5/Dockerfile) then installing the latest version works fine, but when you go to run it you get the following error 

```bash
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/src/app/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.cls_wrapMethod [as _load] (/usr/src/app/node_modules/newrelic/lib/shimmer.js:247:38)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.cls_wrapMethod [as _load] (/usr/src/app/node_modules/newrelic/lib/shimmer.js:247:38)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/wms/lib/tile.js:7:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by springmeyer** [comment]
To fix this you'll need to do:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y libstdc++-5-dev
```

per https://github.com/mapnik/node-mapnik#depends
