### ISSUE TITLE
Docker install - Cannot find module mapnik_settings.js

### ISSUE THREAD

**Issue by eczajk1** [mapnik/node-mapnik#711]
Tried using node-mapnik with the standard node images.  Couldn't get it to install until switching to [mhart/alpine-node](https://github.com/mhart/alpine-node).

```
FROM mhart/alpine-node:4.6.2

...

RUN apk add --no-cache make gcc g++ python
RUN npm install
```

Seems like everything installs properly during the build, but when I run my app in Docker, I see

```
Error: Cannot find module '/usr/src/app/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/src/app/node_modules/mapnik/lib/mapnik.js:8:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

...which I gather is related to mapbox/mapbox-studio-classic#1091 , but I don't know how to fix in this context.  Any help is appreciated.

**Comment by springmeyer** [comment]
Please provide the entire output of `npm install` from your terminal. There was likely a build failure early on. The classic build failure on docker is that parts of `npm` will not work when run as sudo and you need to pass `--unsafe-perm` to `npm install`.

**Comment by eczajk1** [comment]
```
Step 6 : RUN npm install
 ---> Running in da0a9b98f5f2
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

> mapnik@3.5.14 preinstall /usr/src/app/node_modules/mapnik
> npm install node-pre-gyp

npm WARN package.json mapnik@3.5.14 No license field.
node-pre-gyp@0.6.32 node_modules/node-pre-gyp
├── semver@5.3.0
├── nopt@3.0.6 (abbrev@1.0.9)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rc@1.1.6 (ini@1.3.4, deep-extend@0.4.1, strip-json-comments@1.0.4, minimist@1.2.0)
├── tar@2.2.1 (inherits@2.0.3, block-stream@0.0.9, fstream@1.0.10)
├── tar-pack@3.3.0 (uid-number@0.0.6, once@1.3.3, debug@2.2.0, readable-stream@2.1.5, fstream@1.0.10, fstream-ignore@1.0.5)
├── rimraf@2.5.4 (glob@7.1.1)
├── npmlog@4.0.1 (set-blocking@2.0.0, console-control-strings@1.1.0, are-we-there-yet@1.1.2, gauge@2.7.1)
└── request@2.79.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1.5.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, uuid@3.0.1, qs
@6.3.0, mime-types@2.1.13, combined-stream@1.0.5, tough-cookie@2.3.2, form-data@2.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)

> mapnik@3.5.14 install /usr/src/app/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

[mapnik] Success: "/usr/src/app/node_modules/mapnik/lib/binding/node-v46-linux-x64/mapnik.node" is installed via remote
serve-favicon@2.3.2 node_modules/serve-favicon
├── ms@0.7.2
├── parseurl@1.3.1
├── fresh@0.3.0
└── etag@1.7.0

cookie-parser@1.3.5 node_modules/cookie-parser
├── cookie@0.1.3
└── cookie-signature@1.0.6

debug@2.2.0 node_modules/debug
└── ms@0.7.1

cors@2.8.1 node_modules/cors
└── vary@1.1.0

morgan@1.6.1 node_modules/morgan
├── on-headers@1.0.1
├── basic-auth@1.0.4
├── depd@1.0.1
└── on-finished@2.3.0 (ee-first@1.1.1)

body-parser@1.13.3 node_modules/body-parser
├── bytes@2.1.0
├── content-type@1.0.2
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.3, statuses@1.3.1)
├── iconv-lite@0.4.11
├── type-is@1.6.14 (media-typer@0.3.0, mime-types@2.1.13)
└── raw-body@2.1.7 (unpipe@1.0.0, bytes@2.4.0, iconv-lite@0.4.13)

express@4.13.4 node_modules/express
├── cookie-signature@1.0.6
├── content-type@1.0.2
├── etag@1.7.0
├── fresh@0.3.0
├── parseurl@1.3.1
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── merge-descriptors@1.0.1
├── methods@1.1.2
├── vary@1.0.1
├── cookie@0.1.5
├── content-disposition@0.5.1
├── range-parser@1.0.3
├── path-to-regexp@0.1.7
├── depd@1.1.0
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── type-is@1.6.14 (media-typer@0.3.0, mime-types@2.1.13)
├── send@0.13.1 (ms@0.7.1, destroy@1.0.4, statuses@1.2.1, mime@1.3.4, http-errors@1.3.1)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.13)
└── serve-static@1.10.3 (send@0.13.2)

jade@1.11.0 node_modules/jade
├── commander@2.6.0
├── character-parser@1.2.1
├── void-elements@2.0.1
├── jstransformer@0.0.2 (is-promise@2.1.0, promise@6.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── constantinople@3.0.2 (acorn@2.7.0)
├── with@4.0.3 (acorn@1.2.2, acorn-globals@1.0.9)
├── clean-css@3.4.21 (commander@2.8.1, source-map@0.4.4)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
└── uglify-js@2.7.5 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)

lodash@4.17.2 node_modules/lodash

mapnik@3.5.14 node_modules/mapnik
├── protozero@1.4.5
├── nan@2.4.0
└── mapnik-vector-tile@1.2.2
 ---> 2518e746c119
Removing intermediate container da0a9b98f5f2
```

**Comment by springmeyer** [comment]
Thanks. I see `/usr/src/app/node_modules/mapnik/lib/binding/node-v46-linux-x64/mapnik.node` showing up in the install logs which means that the node-mapnik binary was installed for node ABI version 46 which is node v4.x (lookup at https://nodejs.org/download/release/index.json). But when you run node-mapnik you are running node v0.10.x. And a binary for that version (`ABI v11`) does not exist since you did not install with node v0.10.x
