### ISSUE TITLE
I get "not recognized as a supported file format." with GDAL datasources

### ISSUE THREAD

**Issue by tjwebb** [mapnik/node-mapnik#722]
node: 6.9
node-mapnik: 3.5.14
mapnik: 3.0.12

```
Error: `/home/ubuntu/underbuilt-server/config/mapnik/xml/gdal_osm_basemap_cache.xml' not recognized as a supported file format.
  encountered during parsing of layer 'streets_layer' in Layer of 'config/mapnik/xml/hybrid_basemap.xml'
    at Error (native)
    at Object.<anonymous> (/home/ubuntu/underbuilt-server/node_modules/@langa/mapnik/bin/mapnik-inspect.js:92:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

It works fine if I inspect it with `gdalinfo`. postgis sources seem to work also. this is the file:
```xml
<GDAL_WMS>
  <Service name="TMS">
    <ServerUrl>http://d1gs2ejst5lc1o.cloudfront.net/streets/${z}/${x}/${y}/mq.512px.png</ServerUrl>
    <SRS>EPSG:3857</SRS>
    <Format>png</Format>
    <ImageFormat>image/png</ImageFormat>
    <Transparent>TRUE</Transparent>
  </Service>

  <DataWindow>
    <UpperLeftX>-20037508.34</UpperLeftX>
    <LowerRightX>20037508.34</LowerRightX>
    <UpperLeftY>20037508.34</UpperLeftY>
    <LowerRightY>-20037508.34</LowerRightY>

    <TileLevel>18</TileLevel>
    <TileCountX>1</TileCountX>
    <TileCountY>1</TileCountY>
    <YOrigin>top</YOrigin>
  </DataWindow>

  <Projection>EPSG:3857</Projection>
  <BlockSizeX>512</BlockSizeX>
  <BlockSizeY>512</BlockSizeY>
  <BandsCount>3</BandsCount>
  <MaxConnections>32</MaxConnections>
  <AdviseRead>true</AdviseRead>
  <VerifyAdviseRead>true</VerifyAdviseRead>

  <UnsafeSSL>true</UnsafeSSL>
  <ZeroBlockHttpCodes>204,403,404,500,502,503,504</ZeroBlockHttpCodes>
  <ZeroBlockOnServerException>true</ZeroBlockOnServerException>
</GDAL_WMS>
```

**Comment by tjwebb** [comment]
I've confirmed that my exact same configuration works with
node: 6.9
mapnik: 3.0.9
node-mapnik: aa4e8ee7066f1913fa38319b2373ba5179090ba7

**Comment by flippmoke** [comment]
Please post your xml file. Additionally, the prebuilt GDAL included for node-mapnik does not include all the GDAL drivers -- that might be causing the problem.

**Comment by tjwebb** [comment]
As I mentioned, this works fine with 3.0.9. However, the published 3.0.9-compatible node-mapnik doesn't work with node 6, so I ended up having to use my own custom fork: https://github.com/langateam/node-mapnik. (it also fixes https://github.com/mapnik/node-mapnik/issues/650).

XML file is pretty straightforward. The GDAL xml file is ^^

```xml
<Map srs="+init=epsg:3857" background-color="#ffffffff">
  <Parameters>
    <Parameter name="format">png8</Parameter>
    <Parameter name="tileSize">512</Parameter>
    <Parameter name="width">512</Parameter>
    <Parameter name="height">512</Parameter>
    <Parameter name="minzoom">2</Parameter>
    <Parameter name="maxzoom">18</Parameter>
  </Parameters>

  <Style name="aerial_raster_1ft">
    <Rule>
      <MaxScaleDenominator>20000</MaxScaleDenominator>
      <MinScaleDenominator>12000</MinScaleDenominator>
      <RasterSymbolizer opacity="0.60" />
    </Rule>
    <Rule>
      <MaxScaleDenominator>12000</MaxScaleDenominator>
      <MinScaleDenominator>6000</MinScaleDenominator>
      <RasterSymbolizer opacity="0.75" />
    </Rule>
    <Rule>
      <MaxScaleDenominator>6000</MaxScaleDenominator>
      <MinScaleDenominator>4000</MinScaleDenominator>
      <RasterSymbolizer opacity="0.90" />
    </Rule>
    <Rule>
      <MaxScaleDenominator>4000</MaxScaleDenominator>
      <RasterSymbolizer opacity="1.0" />
    </Rule>
  </Style>

  <Style name="basemap" image-filters="color-to-alpha(#fff)">
    <Rule>
      <RasterSymbolizer opacity="1.0" />
    </Rule>
  </Style>

  <Layer name="imagery_layer" srs="+init=epsg:3857">
    <StyleName>aerial_raster_1ft</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">gdal_wms_nm_orthoimagery_1ft.xml</Parameter>
    </Datasource>
  </Layer>


  <Layer name="streets_layer" srs="+init=epsg:3857">
    <StyleName>basemap</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">gdal_osm_basemap_cache.xml</Parameter>
    </Datasource>
  </Layer>

</Map>
```

**Comment by flippmoke** [comment]
It is likely an issue with the prepackaged GDAL not having the proper driver -- which is why it likely works when you are not using the prepackaged version. 

@springmeyer do we have a way to list the GDAL drivers we support in the prepackaged?

**Comment by tjwebb** [comment]
Is there a way to build just the mapnik gdal plugin against a gdal I know to have the wms driver installed, and then point to that?

Something obviously changed between 3.5.13 and 3.5.14 to cause this, which suggests that 3.5.14 should not have been a patch release...

**Comment by flippmoke** [comment]
It looks like we upgraded to using `GDAL 2.1.1` according to the [changelog](https://github.com/mapnik/node-mapnik/blob/v3.5.14/CHANGELOG.md#3514) on 3.5.14

**Comment by flippmoke** [comment]
Also, it looks like our upgraded version of `mapnik` in that release also changed somethings about the [GDAL driver](https://github.com/mapnik/mapnik/blob/master/CHANGELOG.md#summary). 

/cc @artemp

**Comment by tjwebb** [comment]
so, where does this leave us? It sounds like the issue is maybe due to some new API incompatibility.

**Comment by flippmoke** [comment]
It might be a difference in the prebuilt GDAL drivers we build by default -- but would not call this an API compatibility issue.  You can definitely build your own custom mapnik against a custom version of GDAL -- and then build a custom node-mapnik against that.

**Comment by flippmoke** [comment]
Closing re-open if more support is needed.
