### ISSUE TITLE
Cannot find module 'D:\Intership\Geojsontopng\geojson2png\node_modules\mapnik\lib\binding\node-v48-win32-x64\mapnik_settings.js'

### ISSUE THREAD

**Issue by vantann** [mapnik/node-mapnik#723]
D:\Intership\Geojsontopng\geojson2png>node example2.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Intership\Geojsontopng\geojson2png\node_modules\mapnik\lib\binding\node-v48-win32-x64\mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Intership\Geojsontopng\geojson2png\node_modules\mapnik\lib\mapnik.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Help me Please !

**Comment by flippmoke** [comment]
What version of node are you using? It appears you do not have node mapnik installed properly.

Additionally when you are pasting large amounts of text in a github ticket it always helps to put it in a [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/) IMO.

**Comment by vantann** [comment]
Tks u
