### ISSUE TITLE
Windows install issue - 'mapnik-config' is not recognized as an internal or external command - node.js@6.5.0 / node-mapnik@master

### ISSUE THREAD

**Issue by vjpr** [mapnik/node-mapnik#728]
```
> mapnik@3.5.14 preinstall C:\Users\Vaughan\dev\node-mapnik
> npm install node-pre-gyp

mapnik@3.5.14 C:\Users\Vaughan\dev\node-mapnik
`-- node-pre-gyp@0.6.33


> mapnik@3.5.14 install C:\Users\Vaughan\dev\node-mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@6.5.0 (node-v48 ABI) (falling back to source compile with node-gyp)

Vaughan@DESKTOP-8NHQ0VR C:\Users\Vaughan\dev\node-mapnik
> if not defined npm_config_node_gyp (node "C:\Users\Vaughan\AppData\Roaming\nvm\v6.5.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

Vaughan@DESKTOP-8NHQ0VR C:\Users\Vaughan\dev\node-mapnik
> if not defined npm_config_node_gyp (node "C:\Users\Vaughan\AppData\Roaming\nvm\v6.5.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64\mapnik.node --module_name=mapnik --module_path=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64\mapnik.node --module_name=mapnik --module_path=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64 )
'mapnik-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'mapnik-config --ldflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Vaughan\AppData\Roaming\nvm\v6.5.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vaughan\\AppData\\Roaming\\nvm\\v6.5.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Vaughan\\dev\\node-mapnik\\lib\\binding\\node-v48-win32-x64\\mapnik.node" "--module_name=mapnik" "--module_path=C:\\Users\\Vaughan\\dev\\node-mapnik\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd C:\Users\Vaughan\dev\node-mapnik
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64\mapnik.node --module_name=mapnik --module_path=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Vaughan\dev\node-mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vaughan\\dev\\node-mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Vaughan\dev\node-mapnik
node-pre-gyp ERR! node -v v6.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64\mapnik.node --module_name=mapnik --module_path=C:\Users\Vaughan\dev\node-mapnik\lib\binding\node-v48-win32-x64' (1)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.5.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Vaughan\dev\node-mapnik\npm-debug.log
```

**Comment by flippmoke** [comment]
We could not possibly build all prebuilt binaries for all versions of mapnik due to the costs and time. 

We currently only build a select few versions on windows:

```
0.10.40
4.4.1
5.9.1
```

https://ci.appveyor.com/project/Mapbox/node-mapnik

If you want to build your own binaries you can do so by:

- Building your own mapnik, then building node mapnik

or

- Using our windows prebuilt binaries for mapnik, but building for node-mapnik. You can attempt to follow along with what our  https://github.com/mapnik/node-mapnik/blob/master/scripts/build-appveyor.bat does if you are curious how our build process works for node-mapnik and where the prebuilt mapnik binaries come from.
