### ISSUE TITLE
Invalid cast detected by address sanitizer

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#739]
Added address sanitizer builds in #738 which immediately caught:

```
../src/mapnik_image.cpp:3993:17: runtime error: load of value 999, which is not a valid value for type 'mapnik::composite_mode_e'
    #0 0x7f8ec9334109 in Image::composite(Nan::FunctionCallbackInfo<v8::Value> const&) /home/travis/build/mapnik/node-mapnik/build/../src/mapnik_image.cpp:3993:17
    #1 0x7f8ec8da8127 in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) /home/travis/build/mapnik/node-mapnik/build/../node_modules/nan/nan_callbacks_12_inl.h:174:3
    #2 0x8fbee1 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (/home/travis/.nvm/versions/node/v4.8.0/bin/node+0x8fbee1)
    #3 0x925f10 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>&) (/home/travis/.nvm/versions/node/v4.8.0/bin/node+0x925f10)
    #4 0x92636d in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (/home/travis/.nvm/versions/node/v4.8.0/bin/node+0x92636d)
    #5 0x1c5d8c90963a  (<unknown module>)
SUMMARY: AddressSanitizer: undefined-behavior ../src/mapnik_image.cpp:3993:17 in 
Aborted (core dumped)
```

**Comment by springmeyer** [comment]
Fixed in #738
