### ISSUE TITLE
invalid range detected by address sanitizer

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#740]
Added address sanitizer builds in #738 which immediately caught:

```
  mapnik.Image SVG
../src/mapnik_image.cpp:3100:25: runtime error: value 1e+12 is outside the range of representable values of type 'int'
    #0 0x7f69f0145e1c in Image::EIO_FromSVGBytes(uv_work_s*) /home/travis/build/mapnik/node-mapnik/build/../src/mapnik_image.cpp:3100:25
    #1 0xfa4710 in worker /home/iojs/build/ws/out/../deps/uv/src/threadpool.c:95
    #2 0xfb3848 in uv__thread_start /home/iojs/build/ws/out/../deps/uv/src/unix/thread.c:52
    #3 0x7f69f7b54e99 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7e99)
    #4 0x7f69f788236c  (/lib/x86_64-linux-gnu/libc.so.6+0xf336c)

````

**Comment by springmeyer** [comment]
Closed as part of #738
