### ISSUE TITLE
Installation fails in App Engine environment

### ISSUE THREAD

**Issue by donmccurdy** [mapnik/node-mapnik#792]
Attempting to deploy a hello-world app, including Mapnik, on App Engine fails with this error:

```
Application startup error:

> mapnik-test@1.0.0 start /app
> node index.js

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /app/node_modules/mapnik/lib/binding/lib/libmapnik.so)
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mapnik-test@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik-test@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
```

Everything runs fine locally, on macOS and Node.js v6.9.1. Complete example app below:

package.json

```json
{
  "name": "mapnik-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines" : {
    "node" : ">=6 <7"
  },
  "author": "Don McCurdy <dm@donmccurdy.com>",
  "license": "UNLICENSED",
  "dependencies": {
    "express": "^4.15.3",
    "mapnik": "^3.6.2"
  }
}
```

index.js

```js
const mapnik = require('mapnik');
const express = require('express');

const PORT = process.env.PORT || 3002;

const app = express()
  .get('/', (request, response) => {

    response.send(`
      <!DOCTYPE html>
      <h1>Mapnik</h1>
      <p>Successfully loaded.</p>
    `);

  })
  .listen(PORT);

console.log('Listening on port %d', PORT);
```

app.yaml

```yaml
runtime: nodejs
env: flex
```

Three files above, zipped:

[mapnik-test.zip](https://github.com/mapnik/node-mapnik/files/1180430/mapnik-test.zip)

**Comment by calvinmetcalf** [comment]
this is related to #700, basically debian jessie doens't have the up to date version of glibc

**Comment by springmeyer** [comment]
This will be resolved by the upcoming node-mapnik v3.6.3 release: https://github.com/mapnik/node-mapnik/pull/839

**Comment by springmeyer** [comment]
@donmccurdy would be great however if you could help me test to confirm since. Would you be up for that?

**Comment by donmccurdy** [comment]
@springmeyer sure, how would I test that?

Attempted this:

```
npm i --save github:mapnik/node-mapnik#master
```

... but getting errors:

<details>
<summary>Output</summary>

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.0-dev-98c26bc/node-v48-darwin-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.0-dev-98c26bc and node@6.11.3 (node-v48 ABI, unknown) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node" "/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node /Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/donmccurdy/Desktop/mapnik-test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node" "/Users/donmccurdy/Desktop/mapnik-test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik
node-pre-gyp ERR! node -v v6.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node /Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding' (1)
npm WARN mapnik-test@1.0.0 No description
npm WARN mapnik-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.0-dev-98c26bc install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.7.0-dev-98c26bc install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donmccurdy/.npm/_logs/2018-01-24T22_28_28_160Z-debug.log
```

</details>

**Comment by springmeyer** [comment]
@donmccurdy try this:

```
npm install --save github:mapnik/node-mapnik#v3.0.x
```

**Comment by donmccurdy** [comment]
similar result:

<details>
<summary>Output</summary>

```
mapnik-test  npm install --save github:mapnik/node-mapnik#v3.0.x

> mapnik@3.6.3 install /Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.3/node-v48-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.6.3 and node@6.11.3 (node-v48 ABI, unknown) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node" "/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node /Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/donmccurdy/Desktop/mapnik-test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node" "/Users/donmccurdy/Desktop/mapnik-test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik
node-pre-gyp ERR! node -v v6.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/donmccurdy/.nvm/versions/node/v6.11.3/bin/node /Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/donmccurdy/Desktop/mapnik-test/node_modules/mapnik/lib/binding' (1)
npm WARN mapnik-test@1.0.0 No description
npm WARN mapnik-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.6.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donmccurdy/.npm/_logs/2018-01-24T23_01_37_973Z-debug.log
```

</details>

Environment is macOS:

```
mapnik-test  node -v
v6.11.3
mapnik-test  npm -v
5.6.0
```

**Comment by springmeyer** [comment]
I'm sorry, I assumed you were running on linux (assuming that is the platform that `App Engine` runs on). At this time only linux binaries are available, so testing on a mac is not supported (due to https://www.traviscistatus.com/incidents/1p7kw5hl4n1g).

So, can you test on `App Engine` at this time?

**Comment by donmccurdy** [comment]
Oops, yes I can just deploy to App Engine without testing locally. Result looks similar unfortunately:

<details>
<summary>Output</summary>

```
Step #1: > mapnik@3.6.3 install /app/node_modules/mapnik
Step #1: > node-pre-gyp install --fallback-to-build
Step #1:
Step #1: [mapnik] Success: "/app/node_modules/mapnik/lib/binding/mapnik.node" is installed via remote
Step #1: mapnik-test@1.0.0 /app
Step #1: +-- express@4.16.2
Step #1: | +-- accepts@1.3.4
Step #1: | | +-- mime-types@2.1.17
Step #1: | | | `-- mime-db@1.30.0
Step #1: | | `-- negotiator@0.6.1
Step #1: | +-- array-flatten@1.1.1
Step #1: | +-- body-parser@1.18.2
Step #1: | | +-- bytes@3.0.0
Step #1: | | +-- http-errors@1.6.2
Step #1: | | | +-- depd@1.1.1
Step #1: | | | +-- inherits@2.0.3
Step #1: | | | `-- setprototypeof@1.0.3
Step #1: | | +-- iconv-lite@0.4.19
Step #1: | | `-- raw-body@2.3.2
Step #1: | +-- content-disposition@0.5.2
Step #1: | +-- content-type@1.0.4
Step #1: | +-- cookie@0.3.1
Step #1: | +-- cookie-signature@1.0.6
Step #1: | +-- debug@2.6.9
Step #1: | | `-- ms@2.0.0
Step #1: | +-- depd@1.1.2
Step #1: | +-- encodeurl@1.0.2
Step #1: | +-- escape-html@1.0.3
Step #1: | +-- etag@1.8.1
Step #1: | +-- finalhandler@1.1.0
Step #1: | | `-- unpipe@1.0.0
Step #1: | +-- fresh@0.5.2
Step #1: | +-- merge-descriptors@1.0.1
Step #1: | +-- methods@1.1.2
Step #1: | +-- on-finished@2.3.0
Step #1: | | `-- ee-first@1.1.1
Step #1: | +-- parseurl@1.3.2
Step #1: | +-- path-to-regexp@0.1.7
Step #1: | +-- proxy-addr@2.0.2
Step #1: | | +-- forwarded@0.1.2
Step #1: | | `-- ipaddr.js@1.5.2
Step #1: | +-- qs@6.5.1
Step #1: | +-- range-parser@1.2.0
Step #1: | +-- safe-buffer@5.1.1
Step #1: | +-- send@0.16.1
Step #1: | | +-- destroy@1.0.4
Step #1: | | `-- mime@1.4.1
Step #1: | +-- serve-static@1.13.1
Step #1: | +-- setprototypeof@1.1.0
Step #1: | +-- statuses@1.3.1
Step #1: | +-- type-is@1.6.15
Step #1: | | `-- media-typer@0.3.0
Step #1: | +-- utils-merge@1.0.1
Step #1: | `-- vary@1.1.2
Step #1: `-- mapnik@3.6.3  (git://github.com/mapnik/node-mapnik.git#1cccdfa049fb794ed084320f8b1d824832a8eba1)
Step #1:   +-- mapnik-vector-tile@1.4.0
Step #1:   +-- nan@2.8.0
Step #1:   +-- node-pre-gyp@0.6.39
Step #1:   | +-- detect-libc@1.0.3
Step #1:   | +-- hawk@3.1.3
Step #1:   | | +-- boom@2.10.1
Step #1:   | | +-- cryptiles@2.0.5
Step #1:   | | +-- hoek@2.16.3
Step #1:   | | `-- sntp@1.0.9
Step #1:   | +-- mkdirp@0.5.1
Step #1:   | | `-- minimist@0.0.8
Step #1:   | +-- nopt@4.0.1
Step #1:   | | +-- abbrev@1.1.1
Step #1:   | | `-- osenv@0.1.4
Step #1:   | |   +-- os-homedir@1.0.2
Step #1:   | |   `-- os-tmpdir@1.0.2
Step #1:   | +-- npmlog@4.1.2
Step #1:   | | +-- are-we-there-yet@1.1.4
Step #1:   | | | `-- delegates@1.0.0
Step #1:   | | +-- console-control-strings@1.1.0
Step #1:   | | +-- gauge@2.7.4
Step #1:   | | | +-- aproba@1.2.0
Step #1:   | | | +-- has-unicode@2.0.1
Step #1:   | | | +-- object-assign@4.1.1
Step #1:   | | | +-- signal-exit@3.0.2
Step #1:   | | | +-- string-width@1.0.2
Step #1:   | | | | +-- code-point-at@1.1.0
Step #1:   | | | | `-- is-fullwidth-code-point@1.0.0
Step #1:   | | | |   `-- number-is-nan@1.0.1
Step #1:   | | | +-- strip-ansi@3.0.1
Step #1:   | | | | `-- ansi-regex@2.1.1
Step #1:   | | | `-- wide-align@1.1.2
Step #1:   | | `-- set-blocking@2.0.0
Step #1:   | +-- rc@1.2.4
Step #1:   | | +-- deep-extend@0.4.2
Step #1:   | | +-- ini@1.3.5
Step #1:   | | +-- minimist@1.2.0
Step #1:   | | `-- strip-json-comments@2.0.1
Step #1:   | +-- request@2.81.0
Step #1:   | | +-- aws-sign2@0.6.0
Step #1:   | | +-- aws4@1.6.0
Step #1:   | | +-- caseless@0.12.0
Step #1:   | | +-- combined-stream@1.0.5
Step #1:   | | | `-- delayed-stream@1.0.0
Step #1:   | | +-- extend@3.0.1
Step #1:   | | +-- forever-agent@0.6.1
Step #1:   | | +-- form-data@2.1.4
Step #1:   | | | `-- asynckit@0.4.0
Step #1:   | | +-- har-validator@4.2.1
Step #1:   | | | +-- ajv@4.11.8
Step #1:   | | | | +-- co@4.6.0
Step #1:   | | | | `-- json-stable-stringify@1.0.1
Step #1:   | | | |   `-- jsonify@0.0.0
Step #1:   | | | `-- har-schema@1.0.5
Step #1:   | | +-- http-signature@1.1.1
Step #1:   | | | +-- assert-plus@0.2.0
Step #1:   | | | +-- jsprim@1.4.1
Step #1:   | | | | +-- assert-plus@1.0.0
Step #1:   | | | | +-- extsprintf@1.3.0
Step #1:   | | | | +-- json-schema@0.2.3
Step #1:   | | | | `-- verror@1.10.0
Step #1:   | | | |   `-- assert-plus@1.0.0
Step #1:   | | | `-- sshpk@1.13.1
Step #1:   | | |   +-- asn1@0.2.3
Step #1:   | | |   +-- assert-plus@1.0.0
Step #1:   | | |   +-- bcrypt-pbkdf@1.0.1
Step #1:   | | |   +-- dashdash@1.14.1
Step #1:   | | |   | `-- assert-plus@1.0.0
Step #1:   | | |   +-- ecc-jsbn@0.1.1
Step #1:   | | |   +-- getpass@0.1.7
Step #1:   | | |   | `-- assert-plus@1.0.0
Step #1:   | | |   +-- jsbn@0.1.1
Step #1:   | | |   `-- tweetnacl@0.14.5
Step #1:   | | +-- is-typedarray@1.0.0
Step #1:   | | +-- isstream@0.1.2
Step #1:   | | +-- json-stringify-safe@5.0.1
Step #1:   | | +-- oauth-sign@0.8.2
Step #1:   | | +-- performance-now@0.2.0
Step #1:   | | +-- qs@6.4.0
Step #1:   | | +-- stringstream@0.0.5
Step #1:   | | +-- tough-cookie@2.3.3
Step #1:   | | | `-- punycode@1.4.1
Step #1:   | | +-- tunnel-agent@0.6.0
Step #1:   | | `-- uuid@3.2.1
Step #1:   | +-- rimraf@2.6.2
Step #1:   | | `-- glob@7.1.2
Step #1:   | |   +-- fs.realpath@1.0.0
Step #1:   | |   +-- inflight@1.0.6
Step #1:   | |   +-- minimatch@3.0.4
Step #1:   | |   | `-- brace-expansion@1.1.8
Step #1:   | |   |   +-- balanced-match@1.0.0
Step #1:   | |   |   `-- concat-map@0.0.1
Step #1:   | |   `-- path-is-absolute@1.0.1
Step #1:   | +-- semver@5.5.0
Step #1:   | +-- tar@2.2.1
Step #1:   | | +-- block-stream@0.0.9
Step #1:   | | `-- fstream@1.0.11
Step #1:   | |   `-- graceful-fs@4.1.11
Step #1:   | `-- tar-pack@3.4.1
Step #1:   |   +-- fstream-ignore@1.0.5
Step #1:   |   +-- once@1.4.0
Step #1:   |   | `-- wrappy@1.0.2
Step #1:   |   +-- readable-stream@2.3.3
Step #1:   |   | +-- core-util-is@1.0.2
Step #1:   |   | +-- isarray@1.0.0
Step #1:   |   | +-- process-nextick-args@1.0.7
Step #1:   |   | +-- string_decoder@1.0.3
Step #1:   |   | `-- util-deprecate@1.0.2
Step #1:   |   `-- uid-number@0.0.6
Step #1:   `-- protozero@1.5.1
Step #1:
Step #1: npm WARN mapnik-test@1.0.0 No description
Step #1: npm WARN mapnik-test@1.0.0 No repository field.
Step #1:  ---> 3643d607a84a
Step #1: Removing intermediate container 50af60b68ead
Step #1: Step 5/5 : CMD npm start
Step #1:  ---> Running in 6761448063fa
Step #1:  ---> 83d8a5900703
Step #1: Removing intermediate container 6761448063fa
Step #1: Successfully built 83d8a5900703
Step #1: Successfully tagged us.gcr.io/donmccurdy-dev/appengine/default.20180124t151644:latest
Finished Step #1
PUSH
Pushing us.gcr.io/donmccurdy-dev/appengine/default.20180124t151644:latest
The push refers to a repository [us.gcr.io/donmccurdy-dev/appengine/default.20180124t151644]
9206c37396d8: Preparing
97135bd959da: Preparing
cadcc7c01314: Preparing
bc37093ecf8a: Preparing
b0532b80ed9e: Preparing
87c9a22fb286: Preparing
34b3438ad618: Preparing
de5e96f3b52d: Preparing
647127451460: Preparing
0529bceacd9f: Preparing
21df82f90a72: Preparing
87c9a22fb286: Waiting
34b3438ad618: Waiting
de5e96f3b52d: Waiting
647127451460: Waiting
0529bceacd9f: Waiting
21df82f90a72: Waiting
bc37093ecf8a: Layer already exists
b0532b80ed9e: Layer already exists
87c9a22fb286: Layer already exists
34b3438ad618: Layer already exists
de5e96f3b52d: Layer already exists
647127451460: Layer already exists
0529bceacd9f: Layer already exists
21df82f90a72: Layer already exists
cadcc7c01314: Pushed
97135bd959da: Pushed
9206c37396d8: Pushed
latest: digest: sha256:fec83d5d68e5b0a3d9d0f8ed2808381361dd847782ef6384bdcbba9f116af036 size: 2628
DONE
-------------------------------------------------------------------------------------------------------------------------------------

Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:

> mapnik-test@1.0.0 start /app
> node index.js

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /app/node_modules/mapnik/lib/binding/lib/libmapnik.so)
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Linux 3.16.0-5-amd64
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mapnik-test@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik-test@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
```

</details>

**Comment by springmeyer** [comment]
Thanks. Must be a glitch in my work. I’ll reopen and take another look tomorrow. Based on the error I should be able to replicate on my local docker instance.

**Comment by springmeyer** [comment]
@donmccurdy okay, found the glitch (mapnik package needed rebuilt). Can you try again:

```
npm cache clean
npm install github:mapnik/node-mapnik#v3.0.x
```

See if that now works?

**Comment by donmccurdy** [comment]
It works! 🙂

<img width="582" alt="screen shot 2018-01-25 at 2 21 18 pm" src="https://user-images.githubusercontent.com/1848368/35415616-10b1bbb6-01db-11e8-9894-2bcf925ffeab.png">

The specific steps to test this, starting from my code posted above, were to change dependencies in `package.json`:

```
"dependencies": {
  "express": "^4.15.3",
  "mapnik": "github:mapnik/node-mapnik#v3.0.x"
}
```

and then run `gcloud app deploy --project <project-id>`.

Thanks!

**Comment by springmeyer** [comment]
Right on. Thanks again for testing. So, this should continue working once the formal v3.6.3 release is out (or 3.7.0).
