### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by materer** [mapnik/node-mapnik#831]
I overwrote the existing mapnik.node file after compiling node-mapnik 3.6.2
And run it using node.js:
```
$ node app.js 
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/beemap/work/dabeeo_vector_tile/node_modules/mapnik/lib/binding/mapnik.node: undefined symbol: _ZN6mapnik8geometry8envelopeIN6mapbox8geometry7polygonIdSt6vectorEEEENS_5box2dINT_15coordinate_typeEEERKS8_
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/beemap/work/dabeeo_vector_tile/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```
Of course, there was no problem in the compilation process
I want to know what is the problem.

**Comment by flippmoke** [comment]
@materer do you have more then one copy of node mapnik in your path?

**Comment by springmeyer** [comment]
Yes, a duplicate mapnik core install sounds like the culprit. This should be fixable be uninstalling your externally installed mapnik library and re-installing node-mapnik. If you still are having trouble please re-open a new issue.
