### ISSUE TITLE
Install from npm failing on OS X

### ISSUE THREAD

**Issue by epall** [mapnik/node-mapnik#833]
OS X 10.13.2
mapnik 3.0.17 (via Homebrew)

From the Clang errors it looks like the versions of `mapnik` and `node-mapnik` are incompatible. Is the expected version of `mapnik` documented somewhere?

```
$ npm install mapnik
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason

> mapnik@3.6.2 install /Users/epall/x/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.2/node-v59-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.6.2 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)
  ACTION binding_gyp_make_vector_tile_target_generate_setting Release/obj/gen/mapnik_settings.js
sh: ./mason_packages/.link/bin/mapnik-config: No such file or directory
sh: ./mason_packages/.link/bin/mapnik-config: No such file or directory
  COPY /Users/epall/x/node_modules/mapnik/lib/binding/mapnik_settings.js
  TOUCH Release/obj.target/make_vector_tile.stamp
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
In file included from ../src/mapnik_logger.cpp:1:
In file included from ../src/utils.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/mapnik/src/node_mapnik.o
In file included from ../src/node_mapnik.cpp:5:
In file included from ../src/mapnik_vector_tile.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/mapnik/src/blend.o
In file included from ../src/blend.cpp:22:
In file included from ../src/mapnik_palette.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/mapnik/src/mapnik_map.o
In file included from ../src/mapnik_map.cpp:1:
In file included from ../src/mapnik_map.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/mapnik_map.cpp:15:
In file included from ../../mapnik-vector-tile/src/vector_tile_processor.hpp:202:
In file included from ../../mapnik-vector-tile/src/vector_tile_processor.ipp:6:
In file included from ../../mapnik-vector-tile/src/vector_tile_strategy.hpp:23:
../../mapnik-vector-tile/src/boost_geometry_adapters.hpp:24:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
                               ^
../src/mapnik_map.cpp:1459:69: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    info.GetReturnValue().Set(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                                    ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings generated.
  CXX(target) Release/obj.target/mapnik/src/mapnik_color.o
In file included from ../src/mapnik_color.cpp:1:
In file included from ../src/mapnik_color.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_color.cpp:186:63: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings generated.
  CXX(target) Release/obj.target/mapnik/src/mapnik_geometry.o
In file included from ../src/mapnik_geometry.cpp:1:
In file included from ../src/utils.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_geometry.cpp:91:63: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings generated.
  CXX(target) Release/obj.target/mapnik/src/mapnik_feature.o
In file included from ../src/mapnik_feature.cpp:1:
In file included from ../src/utils.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_feature.cpp:117:73: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        info.GetReturnValue().Set(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                                        ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_feature.cpp:135:63: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings generated.
  CXX(target) Release/obj.target/mapnik/src/mapnik_image.o
In file included from ../src/mapnik_image.cpp:25:
In file included from ../src/mapnik_image.hpp:7:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:1618:81: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        v8::Local<v8::Object> image_obj = Nan::New(constructor)->GetFunction()->NewInstance(1, &ext);
                                                                                ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:1736:67: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                                  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:2080:81: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        v8::Local<v8::Object> image_obj = Nan::New(constructor)->GetFunction()->NewInstance(1, &ext);
                                                                                ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:2266:67: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                                  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:2375:75: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
                return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                                          ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:2511:81: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        v8::Local<v8::Object> image_obj = Nan::New(constructor)->GetFunction()->NewInstance(1, &ext);
                                                                                ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:2632:17: error: invalid argument type 'void' to unary expression
            if (!p.parse(TOSTR(info[0])))
                ^~~~~~~~~~~~~~~~~~~~~~~~
../src/mapnik_image.cpp:2636:40: error: no member named 'error_messages' in 'mapnik::svg::svg_parser'
                auto const& errors = p.error_messages();
                                     ~ ^
../src/mapnik_image.cpp:2653:17: error: invalid argument type 'void' to unary expression
            if (!p.parse_from_string(svg_buffer))
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/mapnik_image.cpp:2657:40: error: no member named 'error_messages' in 'mapnik::svg::svg_parser'
                auto const& errors = p.error_messages();
                                     ~ ^
../src/mapnik_image.cpp:2721:67: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                                  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:2864:13: error: invalid argument type 'void' to unary expression
        if (!p.parse(closure->filename))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/mapnik_image.cpp:2868:36: error: no member named 'error_messages' in 'mapnik::svg::svg_parser'
            auto const& errors = p.error_messages();
                                 ~ ^
../src/mapnik_image.cpp:2958:81: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        v8::Local<v8::Object> image_obj = Nan::New(constructor)->GetFunction()->NewInstance(1, &ext);
                                                                                ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:3080:13: error: invalid argument type 'void' to unary expression
        if (!p.parse_from_string(svg_buffer))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/mapnik_image.cpp:3084:36: error: no member named 'error_messages' in 'mapnik::svg::svg_parser'
            auto const& errors = p.error_messages();
                                 ~ ^
../src/mapnik_image.cpp:3173:81: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        v8::Local<v8::Object> image_obj = Nan::New(constructor)->GetFunction()->NewInstance(1, &ext);
                                                                                ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:3291:85: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        v8::Local<v8::Value> image_instance = Nan::New(constructor)->GetFunction()->NewInstance(1, &ext);
                                                                                    ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:3346:71: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
            return scope.Escape(Nan::New(constructor)->GetFunction()->NewInstance(1, &ext));
                                                                      ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/mapnik_image.cpp:3515:81: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        v8::Local<v8::Object> image_obj = Nan::New(constructor)->GetFunction()->NewInstance(1, &ext);
                                                                                ^
/Users/epall/.node-gyp/9.3.0/include/node/v8.h:3843:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/epall/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
13 warnings and 8 errors generated.
make: *** [Release/obj.target/mapnik/src/mapnik_image.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/epall/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/epall/homebrew/Cellar/node/9.3.0_1/bin/node" "/Users/epall/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/epall/x/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/epall/x/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/epall/x/node_modules/mapnik
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/epall/homebrew/Cellar/node/9.3.0_1/bin/node /Users/epall/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/epall/x/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/epall/x/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/epall/x/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/Users/epall/homebrew/Cellar/node/9.3.0_1/bin/node" "/Users/epall/x/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/epall/x/node_modules/mapnik
node-pre-gyp ERR! node -v v9.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/Users/epall/homebrew/Cellar/node/9.3.0_1/bin/node /Users/epall/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/epall/x/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/epall/x/node_modules/mapnik/lib/binding' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/epall/x/package.json'
npm WARN x No description
npm WARN x No repository field.
npm WARN x No README data
npm WARN x No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.6.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.6.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/epall/.npm/_logs/2018-01-14T03_01_30_944Z-debug.log
```

**Comment by guigrpa** [comment]
Have you tried installing with Node 8.x?

**Comment by epall** [comment]
Installing with Node v8.9.4 works great.

**Comment by guigrpa** [comment]
Yes, I'm also using Node v8.x for the time being (which is also the supported LTS version). Is there support for Node v9.x in the roadmap?

**Comment by springmeyer** [comment]
The v3.0.x branch should work with Node v9 and therefore the upcoming v3.6.3 release will also work with node v9. Let me know if you find otherwise.

**Comment by guigrpa** [comment]
Great news!

**Comment by tewrisFront** [comment]
I got this error.
I am using node v8.6.0
How can I fix?

**Comment by flippmoke** [comment]
@tewrisFront can you give more information? Feel free to open a new issue if you need to
