### ISSUE TITLE
undefined symbol error, multiple node-mapnik installs?

### ISSUE THREAD

**Issue by eczajk1** [mapnik/node-mapnik#899]
I have an automated build/test that gives me this error when I try to run a unit test:

```
Error: /root/repo/node_modules/mapnik/lib/binding/mapnik.node: undefined symbol: _ZN6mapnik3svg10svg_parserC1ERNS0_13svg_converterINS0_12path_adapterINS0_18vertex_stl_adapterISt6vectorIN3agg11vertex_baseIdEESaIS8_EEEEEESt5dequeINS0_15path_attributesESaISE_EEEEb
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/repo/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/repo/node_modules/tilestrata-blend/index.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/repo/routes/inventory-tiles.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/repo/app.js:9:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/repo/test/health.test.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /root/repo/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (native)
    at Mocha.loadFiles (/root/repo/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/root/repo/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/root/repo/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! Test failed.  See above for more details.
Exited with code 1
```

I gather from other issues that my problem might be related to `node-mapnik` being installed twice, which seems to be true, looking at the install logs (versions 4.0.1 and 3.7.2). But I'm not sure I understand why the two versions are being installed or how to fix.

Mapnik is not a direct dependency of my application, but is required for `tilestrata-mapnik`. When I install locally, I get both versions, but no error:

```
npm install --unsafe-perm

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
\npm WARN engine supertest@3.3.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN peerDependencies The peer dependency mapnik@* included from tilestrata-blend will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
|-npm WARN deprecated tilebelt@1.0.1: This module is now under the @mapbox namespace: install @mapbox/tilebelt instead
\|npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
/\npm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead
||/-|/-npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
\/-|/\\npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
 

> microtime@2.1.8 install /root/repo/node_modules/tilestrata/node_modules/microtime
> prebuild-install || node-gyp rebuild

|///\|-
> mapnik@4.0.1 install /root/repo/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
\[mapnik] Success: "/root/repo/node_modules/mapnik/lib/binding/mapnik.node" is installed via remote
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
 

> mapnik@3.7.2 install /root/repo/node_modules/tilestrata-mapnik/node_modules/tilelive-mapnik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

/[mapnik] Success: "/root/repo/node_modules/tilestrata-mapnik/node_modules/tilelive-mapnik/node_modules/mapnik/lib/binding/mapnik.node" is installed via remote
expect.js@0.3.1 node_modules/expect.js

dotenv@4.0.0 node_modules/dotenv

tilestrata-dependency@0.5.1 node_modules/tilestrata-dependency

@mapbox/tilebelt@1.0.1 node_modules/@mapbox/tilebelt

serve-favicon@2.3.2 node_modules/serve-favicon
├── ms@0.7.2
├── parseurl@1.3.2
├── etag@1.7.0
└── fresh@0.3.0

cookie-parser@1.3.5 node_modules/cookie-parser
├── cookie@0.1.3
└── cookie-signature@1.0.6

debug@2.2.0 node_modules/debug
└── ms@0.7.1

tilestrata-utfmerge@0.1.3 node_modules/tilestrata-utfmerge
├── tilestrata-dependency@0.4.1
└── async@1.5.2

cors@2.8.4 node_modules/cors
├── object-assign@4.1.1
└── vary@1.1.2

morgan@1.6.1 node_modules/morgan
├── on-headers@1.0.1
├── basic-auth@1.0.4
├── depd@1.0.1
└── on-finished@2.3.0 (ee-first@1.1.1)

bluebird@3.5.2 node_modules/bluebird

body-parser@1.13.3 node_modules/body-parser
├── bytes@2.1.0
├── content-type@1.0.4
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.3, statuses@1.5.0)
├── iconv-lite@0.4.11
├── raw-body@2.1.7 (unpipe@1.0.0, bytes@2.4.0, iconv-lite@0.4.13)
└── type-is@1.6.16 (media-typer@0.3.0, mime-types@2.1.21)

express@4.13.4 node_modules/express
├── cookie-signature@1.0.6
├── content-type@1.0.4
├── etag@1.7.0
├── fresh@0.3.0
├── parseurl@1.3.2
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── merge-descriptors@1.0.1
├── methods@1.1.2
├── vary@1.0.1
├── cookie@0.1.5
├── content-disposition@0.5.1
├── range-parser@1.0.3
├── path-to-regexp@0.1.7
├── depd@1.1.2
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.2, ipaddr.js@1.0.5)
├── send@0.13.1 (destroy@1.0.4, ms@0.7.1, statuses@1.2.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.16 (media-typer@0.3.0, mime-types@2.1.21)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.21)
└── serve-static@1.10.3 (send@0.13.2)

mocha@5.2.0 node_modules/mocha
├── escape-string-regexp@1.0.5
├── browser-stdout@1.3.1
├── commander@2.15.1
├── he@1.1.1
├── growl@1.10.5
├── supports-color@5.4.0 (has-flag@3.0.0)
├── debug@3.1.0 (ms@2.0.0)
├── diff@3.5.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── minimatch@3.0.4 (brace-expansion@1.1.11)
└── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6)

supertest@3.3.0 node_modules/supertest
├── methods@1.1.2
└── superagent@3.8.3 (cookiejar@2.1.2, component-emitter@1.2.1, extend@3.0.2, mime@1.6.0, formidable@1.2.1, qs@6.5.2, debug@3.2.6, form-data@2.3.3, readable-stream@2.3.6)

yargs@11.1.0 node_modules/yargs
├── decamelize@1.2.0
├── get-caller-file@1.0.3
├── y18n@3.2.1
├── set-blocking@2.0.0
├── which-module@2.0.0
├── require-main-filename@1.0.1
├── require-directory@2.1.1
├── yargs-parser@9.0.2 (camelcase@4.1.0)
├── string-width@2.1.1 (is-fullwidth-code-point@2.0.0, strip-ansi@4.0.0)
├── cliui@4.1.0 (strip-ansi@4.0.0, wrap-ansi@2.1.0)
├── find-up@2.1.0 (locate-path@2.0.0)
└── os-locale@2.1.0 (lcid@1.0.0, mem@1.1.0, execa@0.7.0)

jade@1.11.0 node_modules/jade
├── commander@2.6.0
├── character-parser@1.2.1
├── void-elements@2.0.1
├── jstransformer@0.0.2 (is-promise@2.1.0, promise@6.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── constantinople@3.0.2 (acorn@2.7.0)
├── with@4.0.3 (acorn@1.2.2, acorn-globals@1.0.9)
├── clean-css@3.4.28 (commander@2.8.1, source-map@0.4.4)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
└── uglify-js@2.8.29 (uglify-to-browserify@1.0.2, source-map@0.5.7, yargs@3.10.0)

tilestrata@2.1.2 node_modules/tilestrata
├── async@1.4.2
├── basic-auth@1.0.3
├── http-status@0.2.5
├── tilebelt@1.0.1
├── humanize-duration@3.3.0
├── filesize@3.1.3
├── uuid@3.3.2
├── recovery@0.2.6 (demolish@1.0.2, tick-tock@1.0.0, eventemitter3@1.1.1, millisecond@0.1.2, one-time@0.0.4)
├── npmlog@1.2.1 (ansi@0.3.1, gauge@1.2.7, are-we-there-yet@1.0.6)
├── microtime@2.1.8 (bindings@1.3.0, nan@2.10.0, prebuild-install@2.5.3)
├── bbox-intersect@0.1.1 (tape@2.14.1)
├── request@2.81.0 (aws-sign2@0.6.0, oauth-sign@0.8.2, tunnel-agent@0.6.0, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.12.0, safe-buffer@5.1.2, stringstream@0.0.6, aws4@1.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.2, performance-now@0.2.0, qs@6.4.0, mime-types@2.1.21, combined-stream@1.0.7, tough-cookie@2.3.4, form-data@2.1.4, hawk@3.1.3, http-signature@1.1.1, har-validator@4.2.1)
└── lodash@3.10.1

mapnik@4.0.1 node_modules/mapnik
├── nan@2.10.0
├── mapnik-vector-tile@2.2.1
└── node-pre-gyp@0.10.3 (detect-libc@1.0.3, semver@5.6.0, rc@1.2.8, mkdirp@0.5.1, nopt@4.0.1, rimraf@2.6.2, npm-packlist@1.1.12, tar@4.4.6, npmlog@4.1.2, needle@2.2.4)

tilestrata-blend@0.3.4 node_modules/tilestrata-blend
├── async@1.4.2
├── tilestrata-dependency@0.4.1
├── fs-extra@0.24.0 (path-is-absolute@1.0.1, jsonfile@2.4.0, graceful-fs@4.1.11, rimraf@2.6.2)
└── lodash@3.10.1

tilestrata-s3@0.1.5 node_modules/tilestrata-s3
├── @turf/bbox-polygon@5.1.5 (@turf/helpers@5.1.5)
├── @turf/intersect@5.1.6 (@turf/clean-coords@5.1.5, @turf/invariant@5.2.0, @turf/helpers@5.1.5, @turf/truncate@5.1.5, turf-jsts@1.2.3)
├── lodash@4.17.11
└── @mapbox/tilelive-s3@6.7.0 (agentkeepalive@2.2.0, @mapbox/tiletype@0.3.1, s3urls@1.5.2, aws-sdk@2.346.0)

tilestrata-mapnik@0.4.1 node_modules/tilestrata-mapnik
├── lodash@3.10.1
└── tilelive-mapnik@0.6.18 (mime@1.3.6, step@0.0.6, generic-pool@2.4.6, sphericalmercator@1.0.5, mapnik@3.7.2)

```

Other similar issues:
- https://github.com/mapnik/node-mapnik/issues/831
- https://github.com/mojodna/tessera/issues/9

**Comment by eczajk1** [comment]
This was happening because of the blanket `peerDependency` of `tilestrata-blend` on `mapnik`, which was installing the latest (`mapnik@4.0.1`). `tilestrata-mapnik` depends on `mapnik@3`, therefore they were both being installed.
