### ISSUE TITLE
Provide pre-built binaries for node 12

### ISSUE THREAD

**Issue by zdila** [mapnik/node-mapnik#931]
Installation works on the same machine when using node 10.

Full log with node 12:

```
✔ bono:~/fm/freemap-mapnik [master|✚ 2⚑ 1]> npm i

> mapnik@4.2.1 install /home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.2.1/node-v72-linux-x64-Release.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for mapnik@4.2.1 and node@12.9.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
/bin/sh: 1: mapnik-config: not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/martin/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.0-2-amd64
gyp ERR! command "/home/martin/.nvm/versions/node/v12.9.1/bin/node" "/home/martin/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik/lib/binding" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/martin/.nvm/versions/node/v12.9.1/bin/node /home/martin/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik/lib/binding --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/martin/fm/freemap-mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.2.0-2-amd64
node-pre-gyp ERR! command "/home/martin/.nvm/versions/node/v12.9.1/bin/node" "/home/martin/fm/freemap-mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik
node-pre-gyp ERR! node -v v12.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/home/martin/.nvm/versions/node/v12.9.1/bin/node /home/martin/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/home/martin/fm/freemap-mapnik/node_modules/freemap-mapserver/node_modules/mapnik/lib/binding --napi_version=4 --node_abi_napi=napi' (1)
npm WARN freemap-mapnik@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/freemap-mapserver/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@4.2.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@4.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martin/.npm/_logs/2019-10-01T17_40_55_938Z-debug.log
```

Thank you!

**Comment by Algunenano** [comment]
Support for node 12 was added in 4.3.0, so you'll need to update

**Comment by zdila** [comment]
I apologize, it was my fault (npm linking vs github dependency). Thanks for fast feedback!
